### ISSUE TITLE
Handling workflow/job cancelling

### ISSUE THREAD

**Issue by chamini2** [ben-z/gh-action-mutex#6]
Is it possible to run the post run step even if the action was cancelled? I have had to delete the generated branches and restart all stuck jobs because of cancelling a running job.

**Comment by ben-z** [comment]
Not currently! Though deleting the generated branch and restarting jobs is not necessary. You can delete the line in the generated file that corresponds to the lock held by the job that was cancelled.

One workaround is to add a timeout (#4) so that eventually, all jobs would complete. Another option is to integrate some GitHub API to check if the lock is held by an active job (requires much more work).
